name: Ubuntu20.04, ROS2 Continuous Integration

on:
  push:
  pull_request:
    branches:
    - master
    - devel

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      #
      # Setup the machines and build environment
      #
      - name: Install ROS.
        uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: foxy

      #
      # Checkout the current branch
      #
      - uses: actions/checkout@v2

      #
      # Build and test the repo
      #
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: dynamic_graph_bridge_msgs
          target-ros2-distro: foxy
