name: Ubuntu20.04, ROS1 Continuous Integration

on:
  push:
    branches:
    - master
    - devel
    - mnaveau/ubuntu20.04_ros1_ros2
  pull_request:
    branches:
    - master
    - devel

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      #
      # Setup the machines and build environment
      #
      - name: Install ROS.
        uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: noetic

      #
      # Checkout the current branch
      #
      - uses: actions/checkout@v2

      #
      # Clone the dependencies in the ROS workspace
      #
      - name: Clone dependencies in the current workspace.
        shell: bash
        run: |
          mkdir -p /home/runner/work/dynamic_graph_bridge/dynamic_graph_bridge/ros_ws/src
          cd /home/runner/work/dynamic_graph_bridge/dynamic_graph_bridge/ros_ws/src
          git clone --recursive https://github.com/stack-of-tasks/dynamic_graph_bridge_msgs.git

      #
      # Build and test the repo
      #
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: dynamic_graph_bridge
          target-ros1-distro: noetic
